### Registrar usuario
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "juanitososo",
    "email": "juanitososo@email.com",
    "password": "123456"
}

### Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "juanitososo",
    "password": "123456"
}

### Crear tarea
POST http://127.0.0.1:8000/api/tasks/create/
Content-Type: application/json

{
    "title": "Finalizar",
    "description": "Backend de TaskFlow",
    "priority": "alta",
    "due_date": "2026-03-20",
    "estado": "pendiente",
    "assigned_to": "juanitososo"
}

### Ver tareas
GET http://127.0.0.1:8000/api/tasks/

### Actualizar tarea (title/desc)
PUT http://127.0.0.1:8000/api/tasks/jAlQ8F7pIGJTv8Rrs64c/update/
Content-Type: application/json

{
    "titulo": "Proyecto actualizado",
    "descripcion": "Backend completado",
    "estado": "completada"
}

### Contador tareas
GET http://127.0.0.1:8000/api/tasks/counter/

### Eliminar tarea
DELETE http://127.0.0.1:8000/api/tasks/jAlQ8F7pIGJTv8Rrs64c/delete/
